<script src="https://giscus.app/client.js"
        data-repo="prodgang/bookofprimes"
        data-repo-id="R_kgDON0JbjQ"
        data-category="Announcements"
        data-category-id="DIC_kwDON0Jbjc4Coer_"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>